language: c
before_install:
        - sudo add-apt-repository -y ppa:snaipewastaken/ppa
        - sudo apt-get update
install:
        - sudo apt-get install -y criterion-dev
script:
       - cd tests && make && ./statula_tests
       - ./get_code_cov.sh
after_success:
        - bash <(curl -s https://codecov.io/bash)
